global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: wasmflow
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
          - "envoy:8080"
